logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.apache.kafka.clients.admin: WARN

DATASOURCE_URL: jdbc:postgresql://localhost:5432/zenwave
DATASOURCE_USERNAME: zenwave
DATASOURCE_PASSWORD:
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
